_target_: diffulab.networks.SprintDiT
simple_dit: true
input_channels: 3
output_channels: 3
inner_dim: 512
embedding_dim: 512
num_heads: 8
mlp_ratio: 4
patch_size: 2
encoder_depth: 2
deep_layers_depth: 8
decoder_depth: 2
n_classes: 10
classifier_free: false
use_checkpoint: false
drop_rate: 0.75
