# CIFAR10 dataset configuration
train:
  _target_: diffulab.datasets.ImageNetLatent
  data_path: "data/imagenet"
  local: true
  batch_size: 128
  split: "train"

val:
  _target_: diffulab.datasets.ImageNetLatent
  data_path: "data/imagenet"
  local: true
  batch_size: 128
  split: "val"
